name: mnist_pipeline
steps:
  importer:
    source:
      file: steps/importers
      name: importer
  normalizer:
    source:
      file: steps/normalizers
      name: normalizer
  trainer:
    source:
      file: steps/trainers
      name: trainer
  evaluator:
    source:
      file: steps/evaluators
      name: evaluator